apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-mcp.fullname" . }}-config
data:
  tools_event.json: |-
{{ .Files.Get "src/tools_event.json" | indent 4 }}
  trust-policy.json: |-
{{ .Files.Get "src/trust-policy.json" | indent 4 }}
