apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-mcp.fullname" . }}-config
data:
data:
  server.py: |
{{ .Files.Get "files/server.py" | indent 4 }}
  tools_event.json: |
{{ .Files.Get "files/tools_event.json" | indent 4 }}
