apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-argocd-mcp
  labels:
    app: {{ default .Chart.Name "argocd-mcp" }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ default .Chart.Name "argocd-mcp" }}
  template:
    metadata:
      labels:
        app: {{ default .Chart.Name "argocd-mcp" }}
    spec:
      serviceAccountName: {{ default "default" .Values.serviceAccountName }}
      containers:
        - name: argocd-mcp
          image: "{{ default "python" .Values.image.repository }}:{{ default "3.11-slim" .Values.image.tag }}"
          imagePullPolicy: "{{ default "IfNotPresent" .Values.image.pullPolicy }}"
          command: ["uvicorn"]
          args: ["server:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-argocd-mcp-secret
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-argocd-mcp-config
