apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-mcp.fullname" . }}
  labels:
    app: {{ include "argocd-mcp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "argocd-mcp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "argocd-mcp.name" . }}
    spec:
      serviceAccountName: {{ include "argocd-mcp.serviceAccountName" . }}
      containers:
        - name: argocd-mcp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ include "argocd-mcp.fullname" . }}-secret
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: {{ include "argocd-mcp.fullname" . }}-config
