replicaCount: 1

command:
  - uvicorn

args:
  - server:app
  - --reload
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  ARGOCD_BASE_URL: "http://your-argocd-server-url"

extraEnv: []

livenessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 10

mounts:
  toolsPath: /app/tools.json

service:
  type: ClusterIP       # Use LoadBalancer if you want external access
  port: 8000
