replicaCount: 1

image:
  repository: python
  tag: "3.11-slim"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  ARGOCD_BASE_URL: "http://a96ce0a1205244fe18c697f962963377-131192832.us-east-1.elb.amazonaws.com"
  ARGOCD_API_TOKEN: "yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3NTUwNjM2NTAsImlhdCI6MTc1NTA2MzY1MCwianRpIjoiNzE4M2Q5YjEtMzk3Mi00Y2JlLTgxOWEtMjAxMGMwODk1MGVjIn0.fNFr_g1odoWICEaHAz_Z859Oo3hmzCJKfB1pmXTTm1M"   # override this at deploy time
